#!/usr/bin/env bash
echo rm app
rm -rf app
rm -rf Strudl.app
echo gulp build
gulp build
echo mv app
mv app/Strudl.app .
echo link modules
ln -s ../../../../node_modules ./Strudl.app/Contents/Resources/app/node_modules
echo link js
rm -rf ./Strudl.app/Contents/Resources/app/js
ln -s ../../../../js ./Strudl.app/Contents/Resources/app/js
echo link style
rm -rf ./Strudl.app/Contents/Resources/app/style
ln -s ../../../../style ./Strudl.app/Contents/Resources/app/style
echo link html
rm -f ./Strudl.app/Contents/Resources/app/win.html
ln -s ../../../../win.html ./Strudl.app/Contents/Resources/app/win.html
echo clean
rm -rf app
echo done
