#!/usr/bin/env bash
APP=`sds package.json -k "name" -f "#v"`
RES="./$APP.app/Contents/Resources/app"
echo rm app
rm -rf app
rm -rf "$APP.app"
echo gulp package
gulp package
echo mv app
mv app/"$APP.app" .
echo link modules
ln -s ../../../../node_modules "$RES/node_modules"
echo link js
rm -rf "$RES/js"
ln -s ../../../../js "$RES/js"
echo link style
rm -rf "$RES/style"
ln -s ../../../../style "$RES/style"
echo link html
rm -f "$RES/win.html"
ln -s ../../../../win.html "$RES/win.html"
echo clean
rm -rf app
echo done
