#!/usr/bin/env bash
echo clean
gulp clean
echo bump
gulp bump
APP=`sds package.json -p "name" -r`
VER=`sds package.json -p "version" -r`
echo build $APP v$VER
RES="./$APP.app/Contents/Resources/app"
echo rm app
rm -rf app
rm -rf "bin/$APP.app"
echo package
gulp package
echo mv app
mv "app/$APP.app" bin
rm -rf app
echo tar app
cd bin
tar czf "$APP.app.tgz" "$APP.app"
echo done $APP v$VER
